### ISSUE TITLE
[Scanner] Encfs encrypted upload not possible

### ISSUE THREAD

**Issue by georg90** [havardgulldahl/jottalib#111]
When trying to upload an encfs encrypted folder I get the following error with jotta-scanner:

`````
SAFERUN: Got exception when processing (u'/home/kodi/.local-sorted/WnBkrZtTYyx1ZVTJ6gRSjPZabWWgu9oxPR4HxFjTkvGq8hqd12Van5hiMAreTx7sW50', u'/Jotta/Sync/files/WnBkrZtTYyx1Z$
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/jottalib/scanner.py", line 54, in saferun
    return apply(cmd, args)
  File "/usr/local/lib/python2.7/dist-packages/jottalib/jottacloud.py", line 151, in replace_if_changed
    return resume(localfile, jf, JFS)
  File "/usr/local/lib/python2.7/dist-packages/jottalib/jottacloud.py", line 135, in resume
    _complete = jottafile.resume(lf)
  File "/usr/local/lib/python2.7/dist-packages/jottalib/JFS.py", line 377, in resume
    return self.jfs.up(self.path, data, resume_offset=self.size)
  File "/usr/local/lib/python2.7/dist-packages/jottalib/JFS.py", line 940, in up
    fileobject.seek(resume_offset if resume_offset is not None else 0)
IOError: [Errno 22] Invalid argument
````

"Normal" uploads are working

**Comment by kaistian** [comment]
What is the reason for this error?
I have uploaded several thousand encfs files without a problem, is this something I should expect might happen?

**Comment by sjurtf** [comment]
I've also uploaded a huge number of encfs files on both linux and os x with no issues. 
From the description it seems that @georg90 is not able to upload any encfs files?

Are you still experiencing problems with this @georg90 ?
