### ISSUE TITLE
Problem installing on Win 7 - fails because of xattr 

### ISSUE THREAD

**Issue by sdalgard** [havardgulldahl/jottalib#112]
Hi,
Thank you for making this functionality available :-)
I am trying to test jottalib on windows 7, but the installation fails:

I have first installed Python 3.5.1 and the started on installing jottalib.

When running "pip install jottalib[scanner]" , it ends with the message :
Command "python setup.py egg_info" failed with error code 1 in C:\Users\steffend\AppData\Local\Temp\pip-build-5028kyzf\xattr\

When searching for issues about xattr I find that its not supported 
https://github.com/xattr/xattr/issues/17

Is there a way around this?

Best regards
Steffen Dalgard

I have 
Here is the complete printout from the pip command:
Collecting jottalib[scanner]
  Using cached jottalib-0.4.2-1.tar.gz
Collecting requests (from jottalib[scanner])
  Using cached requests-2.10.0-py2.py3-none-any.whl
Collecting requests-toolbelt (from jottalib[scanner])
  Using cached requests_toolbelt-0.6.1-py2.py3-none-any.whl
Collecting certifi==2015.4.28 (from jottalib[scanner])
  Using cached certifi-2015.04.28-py2.py3-none-any.whl
Collecting clint (from jottalib[scanner])
  Using cached clint-0.5.1.tar.gz
Collecting python-dateutil (from jottalib[scanner])
  Using cached python_dateutil-2.5.3-py2.py3-none-any.whl
Collecting humanize (from jottalib[scanner])
  Using cached humanize-0.5.1.tar.gz
Collecting lxml (from jottalib[scanner])
  Using cached lxml-3.6.0.tar.gz
Collecting six (from jottalib[scanner])
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting xattr (from jottalib[scanner])
  Using cached xattr-0.8.0.tar.gz
    Complete output from command python setup.py egg_info:
    _cffi_backend.c
    ffi.c
    prep_cif.c
    types.c
    win32.c
       Creating library build\temp.win32-3.5\Release\c\_cffi_backend.cp35-win32.lib and object build\temp.win32-3.5\Release\c\_cffi_backend.cp35-win32.exp
    Generating code
    Finished generating code
    
    Installed c:\users\steffend\appdata\local\temp\pip-build-_f5qidb7\xattr\.eggs\cffi-1.6.0-py3.5-win32.egg
    Searching for pycparser
    Reading https://pypi.python.org/simple/pycparser/
    Best match: pycparser 2.14
    Downloading https://pypi.python.org/packages/6d/31/666614af3db0acf377876d48688c5d334b6e493b96d21aa7d332169bee50/pycparser-2.14.tar.gz#md5=a2bc8d28c923b4fe2b2c3b4b51a4f935
    Processing pycparser-2.14.tar.gz
    Writing C:\Users\steffend\AppData\Local\Temp\easy_install-fh60yv2k\pycparser-2.14\setup.cfg
    Running pycparser-2.14\setup.py -q bdist_egg --dist-dir C:\Users\steffend\AppData\Local\Temp\easy_install-fh60yv2k\pycparser-2.14\egg-dist-tmp-pzqwd9hz
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
    zip_safe flag not set; analyzing archive contents...
    Copying pycparser-2.14-py3.5.egg to c:\users\steffend\appdata\local\temp\pip-build-_f5qidb7\xattr\.eggs
    
    Installed c:\users\steffend\appdata\local\temp\pip-build-_f5qidb7\xattr\.eggs\pycparser-2.14-py3.5.egg
    running egg_info
    creating pip-egg-info\xattr.egg-info
    writing pip-egg-info\xattr.egg-info\PKG-INFO
    writing dependency_links to pip-egg-info\xattr.egg-info\dependency_links.txt
    writing top-level names to pip-egg-info\xattr.egg-info\top_level.txt
    writing entry points to pip-egg-info\xattr.egg-info\entry_points.txt
    writing requirements to pip-egg-info\xattr.egg-info\requires.txt
    writing manifest file 'pip-egg-info\xattr.egg-info\SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    _cffi__x480bb259x3f40c4a9.c
    xattr\__pycache__\_cffi__x480bb259x3f40c4a9.c(220): fatal error C1083: Cannot open include file: 'sys/xattr.h': No such file or directory
    Traceback (most recent call last):
      File "c:\users\steffend\appdata\local\programs\python\python35-32\lib\distutils\_msvccompiler.py", line 395, in compile
        self.spawn(args)
      File "c:\users\steffend\appdata\local\programs\python\python35-32\lib\distutils\_msvccompiler.py", line 514, in spawn
        return super().spawn(cmd)
      File "c:\users\steffend\appdata\local\programs\python\python35-32\lib\distutils\ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "c:\users\steffend\appdata\local\programs\python\python35-32\lib\distutils\spawn.py", line 38, in spawn
        _spawn_nt(cmd, search_path, dry_run=dry_run)
      File "c:\users\steffend\appdata\local\programs\python\python35-32\lib\distutils\spawn.py", line 81, in _spawn_nt
        "command %r failed with exit status %d" % (cmd, rc))
    distutils.errors.DistutilsExecError: command 'D:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "c:\users\steffend\appdata\local\temp\pip-build-_f5qidb7\xattr\.eggs\cffi-1.6.0-py3.5-win32.egg\cffi\ffiplatform.py", line 55, in _build
        dist.run_command('build_ext')
      File "c:\users\steffend\appdata\local\programs\python\python35-32\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\steffend\appdata\local\programs\python\python35-32\lib\site-packages\setuptools\command\build_ext.py", line 49, in run
        _build_ext.run(self)
      File "c:\users\steffend\appdata\local\programs\python\python35-32\lib\distutils\command\build_ext.py", line 338, in run
        self.build_extensions()
      File "c:\users\steffend\appdata\local\programs\python\python35-32\lib\distutils\command\build_ext.py", line 447, in build_extensions
        self._build_extensions_serial()
      File "c:\users\steffend\appdata\local\programs\python\python35-32\lib\distutils\command\build_ext.py", line 472, in _build_extensions_serial
        self.build_extension(ext)
      File "c:\users\steffend\appdata\local\programs\python\python35-32\lib\site-packages\setuptools\command\build_ext.py", line 174, in build_extension
        _build_ext.build_extension(self, ext)
      File "c:\users\steffend\appdata\local\programs\python\python35-32\lib\distutils\command\build_ext.py", line 532, in build_extension
        depends=ext.depends)
      File "c:\users\steffend\appdata\local\programs\python\python35-32\lib\distutils\_msvccompiler.py", line 397, in compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'D:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\steffend\AppData\Local\Temp\pip-build-_f5qidb7\xattr\setup.py", line 67, in <module>
        cmdclass={'build': cffi_build},
      File "c:\users\steffend\appdata\local\programs\python\python35-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\steffend\appdata\local\programs\python\python35-32\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\steffend\appdata\local\programs\python\python35-32\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\steffend\appdata\local\programs\python\python35-32\lib\site-packages\setuptools\command\egg_info.py", line 193, in run
        self.find_sources()
      File "c:\users\steffend\appdata\local\programs\python\python35-32\lib\site-packages\setuptools\command\egg_info.py", line 216, in find_sources
        mm.run()
      File "c:\users\steffend\appdata\local\programs\python\python35-32\lib\site-packages\setuptools\command\egg_info.py", line 300, in run
        self.add_defaults()
      File "c:\users\steffend\appdata\local\programs\python\python35-32\lib\site-packages\setuptools\command\egg_info.py", line 329, in add_defaults
        sdist.add_defaults(self)
      File "c:\users\steffend\appdata\local\programs\python\python35-32\lib\site-packages\setuptools\command\sdist.py", line 120, in add_defaults
        build_py = self.get_finalized_command('build_py')
      File "c:\users\steffend\appdata\local\programs\python\python35-32\lib\distutils\cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "c:\users\steffend\appdata\local\programs\python\python35-32\lib\distutils\cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "c:\users\steffend\appdata\local\programs\python\python35-32\lib\site-packages\setuptools\command\build_py.py", line 33, in finalize_options
        orig.build_py.finalize_options(self)
      File "c:\users\steffend\appdata\local\programs\python\python35-32\lib\distutils\command\build_py.py", line 45, in finalize_options
        ('force', 'force'))
      File "c:\users\steffend\appdata\local\programs\python\python35-32\lib\distutils\cmd.py", line 287, in set_undefined_options
        src_cmd_obj.ensure_finalized()
      File "c:\users\steffend\appdata\local\programs\python\python35-32\lib\distutils\cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "C:\Users\steffend\AppData\Local\Temp\pip-build-_f5qidb7\xattr\setup.py", line 15, in finalize_options
        from xattr.lib import ffi
      File "c:\users\steffend\appdata\local\temp\pip-build-_f5qidb7\xattr\xattr\__init__.py", line 12, in <module>
        from .lib import (XATTR_NOFOLLOW, XATTR_CREATE, XATTR_REPLACE,
      File "c:\users\steffend\appdata\local\temp\pip-build-_f5qidb7\xattr\xattr\lib.py", line 596, in <module>
        """, ext_package='xattr')
      File "c:\users\steffend\appdata\local\temp\pip-build-_f5qidb7\xattr\.eggs\cffi-1.6.0-py3.5-win32.egg\cffi\api.py", line 450, in verify
        lib = self.verifier.load_library()
      File "c:\users\steffend\appdata\local\temp\pip-build-_f5qidb7\xattr\.eggs\cffi-1.6.0-py3.5-win32.egg\cffi\verifier.py", line 113, in load_library
        self._compile_module()
      File "c:\users\steffend\appdata\local\temp\pip-build-_f5qidb7\xattr\.eggs\cffi-1.6.0-py3.5-win32.egg\cffi\verifier.py", line 210, in _compile_module
        outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
      File "c:\users\steffend\appdata\local\temp\pip-build-_f5qidb7\xattr\.eggs\cffi-1.6.0-py3.5-win32.egg\cffi\ffiplatform.py", line 29, in compile
        outputfilename = _build(tmpdir, ext, compiler_verbose)
      File "c:\users\steffend\appdata\local\temp\pip-build-_f5qidb7\xattr\.eggs\cffi-1.6.0-py3.5-win32.egg\cffi\ffiplatform.py", line 62, in _build
        raise VerificationError('%s: %s' % (e.__class__.__name__, e))
    cffi.ffiplatform.VerificationError: CompileError: command 'D:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2
    
    ----------------------------------------

**Comment by havardgulldahl** [comment]
Hey @sdalgard! Thank you for reporting. 

I haven't tried installing xattr on windows, but `jotta-scanner` should be able to run on windows. So I have to check around a bit more, but this sounds like a bug to me.
