### ISSUE TITLE
jottalibs 0.5.0 is broken? Getting errors when executing commands

### ISSUE THREAD

**Issue by xiphias256** [havardgulldahl/jottalib#118]
Did install with pip on an Ubuntu 14.04 machine, like this
sudo pip install jottalib[scanner]
I've then exported my username and password to the enviroment variables JOTTACLOUD_USERNAME and JOTTACLOUD_PASSWORD
If I try to run any of the jotta-* commands I get this error
`jotta-scanner
Traceback (most recent call last):
  File "/usr/local/bin/jotta-scanner", line 9, in <module>
    load_entry_point('jottalib==0.5.0', 'console_scripts', 'jotta-scanner')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/jottalib/cli.py", line 38, in <module>
    from jottalib import JFS, __version__
  File "/usr/local/lib/python2.7/dist-packages/jottalib/JFS.py", line 36, in <module>
    import requests_toolbelt
  File "/usr/local/lib/python2.7/dist-packages/requests_toolbelt/__init__.py", line 12, in <module>
    from .adapters import SSLAdapter, SourceAddressAdapter
  File "/usr/local/lib/python2.7/dist-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>
    from .ssl import SSLAdapter
  File "/usr/local/lib/python2.7/dist-packages/requests_toolbelt/adapters/ssl.py", line 16, in <module>
    from .._compat import poolmanager
  File "/usr/local/lib/python2.7/dist-packages/requests_toolbelt/_compat.py", line 22, in <module>
    from urllib3 import connection
ImportError: cannot import name connection
`

**Comment by havardgulldahl** [comment]
Sadly, this seems to be an issue with the version of urllib3 that Ubuntu 14.04 is shipping.

**Comment by havardgulldahl** [comment]
https://github.com/sigmavirus24/requests-toolbelt/issues/121

**Comment by havardgulldahl** [comment]
I will need to investigate a bit. Thanks for your report, @xiphias

**Comment by havardgulldahl** [comment]
@xiphias256 Could you please try to run

    sudo -H pip install --upgrade requests requests_toolbelt urllib3

**Comment by xiphias256** [comment]
Sorry for the long delay. I've upgraded to 16.04 since I reported the issue. It now works (mostly). jotta-scanner is throwing errors, but that is not related to this issue.
