### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by antonhagg** [havardgulldahl/jottalib#124]
Tried the new 0.5.1 and got this error:

`jotta-download test.txt
Traceback (most recent call last):
  File "PATH\Python\Python35\Scripts\jotta-download-script.py", line 9, in <module>
    load_entry_point('jottalib==0.5.1', 'console_scripts', 'jotta-download')()
  File "PATH\python\python35\lib\site-packages\jottalib\cli.py", line 275, in download
    args = parse_args_and_apply_logging_level(parser, argv)
  File "PATH\python\python35\lib\site-packages\jottalib\cli.py", line 79, in parse_args_and_apply_logging_level
    args = parser.parse_args(argv)
  File "PATH\python\python35\lib\argparse.py", line 1726, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "PATH\python\python35\lib\argparse.py", line 1758, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "PATH\python\python35\lib\argparse.py", line 1967, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "PATH\python\python35\lib\argparse.py", line 1923, in consume_positionals
    take_action(action, args)
  File "PATH\python\python35\lib\argparse.py", line 1816, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "PATH\python\python35\lib\argparse.py", line 2257, in _get_values
    value = self._get_value(action, arg_string)
  File "PATH\python\python35\lib\argparse.py", line 2286, in _get_value
    result = type_func(arg_string)
  File "PATH\python\python35\lib\site-packages\jottalib\cli.py", line 94, in commandline_text
    unicode_string = bytestring.decode(sys.getfilesystemencoding())
AttributeError: 'str' object has no attribute 'decode'`

**Comment by antonhagg** [comment]
Hmm, might be because im running 3.5.2...

**Comment by havardgulldahl** [comment]
yes, py3 support is still not complete :(
see #55

**Comment by havardgulldahl** [comment]
This particular issue has been fixed in the git tree, so closing this.

Note that py3 support is still not complete, please follow #55
