### ISSUE TITLE
Read timed out when downloading big files

### ISSUE THREAD

**Issue by antonhagg** [havardgulldahl/jottalib#128]
Still having trouble with timeout when downloading big files
```
Downloading: CIMG0889.AVI, Size:325.9M[################################] 340131840/341698120 - 00:31:26
Traceback (most recent call last):
  File "C:\Python27\Scripts\jotta-download-script.py", line 9, in <module>
    load_entry_point('jottalib==0.4.1.post1', 'console_scripts', 'jotta-download')()
  File "c:\python27\lib\site-packages\jottalib\cli.py", line 351, in download
  File "c:\python27\lib\site-packages\jottalib\JFS.py", line 907, in stream
  File "c:\python27\lib\site-packages\requests\models.py", line 667, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.jottacloud.com', port=443): Read timed out.
```

**Comment by havardgulldahl** [comment]
Hi @antonhagg - Am I reading it correctly, you've been waiting 31 minutes before timeout?

**Comment by havardgulldahl** [comment]
On closer look, it would seem you are running an old install of jottalib here?

> load_entry_point('jottalib==0.4.1.post1', 'console_scripts', 'jotta-download')()
