### ISSUE TITLE
jotta-fuse cannot read/write to cloud.

### ISSUE THREAD

**Issue by j0achim** [havardgulldahl/jottalib#142]
When I try create a file the file can been seen locally but does not actually exist in cloud, any command given returns "Bad Address".

eg:

```
ubuntu:~/.cloud/Jotta/Archive/Test# echo "Hello World!" > TestFile.txt
ubuntu:~/.cloud/Jotta/Archive/Test# ls
ls: cannot access 'TestFile.txt': Bad address
TestFile.txt
```

debug output:

```
DEBUG:fuse.log-mixin:-> opendir /Jotta/Archive/Test ()
DEBUG:fuse.log-mixin:<- opendir 0
DEBUG:fuse.log-mixin:-> getattr /Jotta/Archive/Test (None,)
DEBUG:jottalib.contrib.mwt:get object from cache: ((<jottalib.jottafuse.JottaFuse object at 0x7fa3b43ed7d0>, u'/Jotta/Archive/Test', None), ())
DEBUG:jottalib.contrib.mwt:new object in cache: ((<jottalib.jottafuse.JottaFuse object at 0x7fa3b43ed7d0>, u'/Jotta/Archive/Test', None), ())
DEBUG:jottalib.JFS:getting url: 'https://www.jottacloud.com/jfs/username/Jotta/Archive/Test', extra_headers=None, params=None
DEBUG:urllib3.connectionpool:https://www.jottacloud.com:443 "GET /jfs/username/Jotta/Archive/Test HTTP/1.1" 200 None
DEBUG:fuse.log-mixin:<- getattr {'st_mtime': 1499507159.941763, 'st_mode': 16877, 'st_size': 0, 'st_gid': 0, 'st_uid': 0, 'st_atime': 1499507159.941762}
DEBUG:fuse.log-mixin:-> readdir /Jotta/Archive/Test (0L,)
DEBUG:fuse.log-mixin:<- readdir <generator object readdir at 0x7fa3b1c105a0>
DEBUG:jottalib.JFS:getting url: 'https://www.jottacloud.com/jfs/username/Jotta/Archive/Test', extra_headers=None, params=None
DEBUG:urllib3.connectionpool:https://www.jottacloud.com:443 "GET /jfs/username/Jotta/Archive/Test HTTP/1.1" 200 None
DEBUG:jottalib.JFS:path: u'/Jotta/Archive' + u'Test'
INFO:jottalib.JFS:syncing u'/Jotta/Archive/Test'
DEBUG:jottalib.JFS:path: u'/Jotta/Archive' + u'Test'
DEBUG:jottalib.JFS:getting url: 'https://www.jottacloud.com/jfs/username/Jotta/Archive/Test', extra_headers=None, params=None
DEBUG:urllib3.connectionpool:https://www.jottacloud.com:443 "GET /jfs/username/Jotta/Archive/Test HTTP/1.1" 200 None
DEBUG:jottalib.JFS:path: u'/Jotta/Archive' + u'Test'
DEBUG:jottalib.JFS:path: u'/Jotta/Archive' + u'Test'
DEBUG:jottalib.JFS:path: u'/Jotta/Archive' + u'Test'
DEBUG:jottalib.JFS:path: u'/Jotta/Archive' + u'Test'
DEBUG:fuse.log-mixin:-> getattr /Jotta/Archive/Test/TestFile.txt (None,)
DEBUG:jottalib.contrib.mwt:new object in cache: ((<jottalib.jottafuse.JottaFuse object at 0x7fa3b43ed7d0>, u'/Jotta/Archive/Test/TestFile.txt', None), ())
DEBUG:jottalib.JFS:getting url: 'https://www.jottacloud.com/jfs/username/Jotta/Archive/Test/TestFile.txt', extra_headers=None, params=None
DEBUG:urllib3.connectionpool:https://www.jottacloud.com:443 "GET /jfs/username/Jotta/Archive/Test/TestFile.txt HTTP/1.1" 200 None
DEBUG:fuse.log-mixin:<- getattr '[Unhandled Exception]'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 495, in _wrapper
    return func(*args, **kwargs) or 0
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 511, in getattr
    return self.fgetattr(path, buf, None)
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 759, in fgetattr
    attrs = self.operations('getattr', self._decode_optional_path(path), fh)
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 972, in __call__
    ret = getattr(self, op)(path, *args)
  File "/usr/local/lib/python2.7/dist-packages/jottalib/contrib/mwt.py", line 73, in func
    v = self.cache[key] = f(*args,**kwargs),time.time()
  File "/usr/local/lib/python2.7/dist-packages/jottalib/jottafuse.py", line 173, in getattr
    if not f.tag in ('user', ):
AttributeError: 'JFSCorruptFile' object has no attribute 'tag'
DEBUG:fuse.log-mixin:-> releasedir /Jotta/Archive/Test (0L,)
DEBUG:fuse.log-mixin:<- releasedir 0
```

**Comment by j0achim** [comment]
Appear's that the fuse functionalit is best used when reading and **not** for writing, if I create file locally upload it with scanner, then output is identical to testcase.
