### ISSUE TITLE
Login .netrc not found

### ISSUE THREAD

**Issue by ccdanieldb** [havardgulldahl/jottalib#146]
I think I have it all installed correctly but when I try to upload a file I get the below error.  As you can see I am using the .netrc.  I created the file with nano and have it in the proper format as per the intro start page. 

machine jottacloud.com
  login **yourusername**
  password **yourpassword**

I am sure I am doing something wrong but I do not know what it is.  

daniel@debian:~$ sudo jotta-scanner /home/daniel/Test /Jotta/Archive/Test
[sudo] password for daniel: 
Traceback (most recent call last):
  File "/usr/local/bin/jotta-scanner", line 11, in <module>
    sys.exit(scanner())
  File "/usr/local/lib/python2.7/dist-packages/jottalib/cli.py", line 440, in scanner
    jfs = JFS.JFS()
  File "/usr/local/lib/python2.7/dist-packages/jottalib/JFS.py", line 954, in __init__
    auth = get_auth_info()
  File "/usr/local/lib/python2.7/dist-packages/jottalib/JFS.py", line 88, in get_auth_info
    raise JFSError('Could not find username and password in either env or ~/.netrc, '
jottalib.JFS.JFSError: Could not find username and password in either env or ~/.netrc, you need to add one of these to use these tools
daniel@debian:~$ ls
Desktop    Downloads             jottalib  Pictures  Templates  Videos
Documents  jottacloudclient.log  Music     Public    Test
daniel@debian:~$ cd ..
daniel@debian:/home$ ls
daniel  jottacloudclient.log  netrc
daniel@debian:/home$ nano jottacloudclient.log
daniel@debian:/home$ sudo nano .netrc
daniel@debian:/home$ sudo nano .netrc
daniel@debian:/home$ ls
daniel  jottacloudclient.log  netrc
daniel@debian:/home$ sudo jotta-scanner /home/daniel/Test /Jotta/Archive/Test
Traceback (most recent call last):
  File "/usr/local/bin/jotta-scanner", line 11, in <module>
    sys.exit(scanner())
  File "/usr/local/lib/python2.7/dist-packages/jottalib/cli.py", line 440, in scanner
    jfs = JFS.JFS()
  File "/usr/local/lib/python2.7/dist-packages/jottalib/JFS.py", line 954, in __init__
    auth = get_auth_info()
  File "/usr/local/lib/python2.7/dist-packages/jottalib/JFS.py", line 88, in get_auth_info
    raise JFSError('Could not find username and password in either env or ~/.netrc, '
jottalib.JFS.JFSError: Could not find username and password in either env or ~/.netrc, you need to add one of these to use these tools
daniel@debian:/home$ ^C

**Comment by ghost** [comment]
You should be able to run jotta-scanner as a normal user (without sudo). Currently it's looking for the .netrc file from /root/ instead of /home/daniel/ .

**Comment by Fjodor42** [comment]
`sudo` might actually look in user *`daniel`'s home folder, but as far as I can see, `netrc` (and not `.netrc` - notice the dot) is actually located in `/home/`, not in `/home/daniel/` as it should be.

@rhoeden is absolutely correct that the user `daniel` should be able to run the commands, but as said, `/home/netrc` should be `/home/daniel/.netrc`
