### ISSUE TITLE
Problems uploading files

### ISSUE THREAD

**Issue by EldarAron** [havardgulldahl/jottalib#152]
Hello

I just set up and ran jotta-scanner for the first time and got the fowwlonig error in the logfile:
```
SAFERUN: Got exception when processing ('/media/Media/Images/eldar_play-del-ingles.png', u'/Jotta/Sync/EldARonServer/Media/Images/eldar_play-del-ingles.png', <jottalib.JFS.JFS object at 0x7fd54ce73710>)
Traceback (most recent call last):
  File "/home/eldaron/.local/lib/python2.7/site-packages/jottalib/scanner.py", line 62, in saferun
    return apply(cmd, args)
  File "/home/eldaron/.local/lib/python2.7/site-packages/jottalib/jottacloud.py", line 197, in new
    _new = JFS.up(jottapath, lf)
  File "/home/eldaron/.local/lib/python2.7/site-packages/jottalib/JFS.py", line 1203, in up
    return self.post(url, None, files=files, params=params, extra_headers=headers, upload_callback=upload_callback)
  File "/home/eldaron/.local/lib/python2.7/site-packages/jottalib/JFS.py", line 1121, in post
    r = self.session.post(url, data=m, params=params, headers=headers)
  File "/home/eldaron/.local/lib/python2.7/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/eldaron/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/eldaron/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/eldaron/.local/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error("(32, 'EPIPE')",))
```
The files are on an extra internal HDD mounted as /media/Media
All files and folders are owned by my user/group.

I get the same error over and over for every file. I know the login info is correct because it creates the folder structure in my JottaCloud account.

**Comment by jnylen** [comment]
@EldarAron try using the new jotta-cli
http://docs.jottacloud.com/jottacloud-command-line-tool

**Comment by georg90** [comment]
This one works for me: https://github.com/Fjodor42/jottalib-ng

Hopefully the CLI will be extended soon.

**Comment by EldarAron** [comment]
The jotta-cli worked for me. Thanks @jnylen !
