### ISSUE TITLE
Is this still working ?

### ISSUE THREAD

**Issue by Antwelm** [havardgulldahl/jottalib#157]
(please be kind, I don't understand much of this)
(PS: I´m on MacOS using jotta´s white label Get Sky)

I'm getting this syntax error when I try to mount:
--
mbp$ pip3 show fusepy
Name: fusepy
Version: 3.0.1
Summary: Simple ctypes bindings for FUSE
Home-page: http://github.com/fusepy/fusepy
Author: Giorgos Verigakis
Author-email: verigak@gmail.com
License: ISC
Location: /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages
Requires: 
Required-by: 

mbp$ jotta-fuse /Users/mbp/mount/getsky
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/jotta-fuse", line 11, in <module>
    load_entry_point('jottalib==0.5.1', 'console_scripts', 'jotta-fuse')()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jottalib/cli.py", line 116, in fuse
    from .jottafuse import JottaFuse
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jottalib/jottafuse.py", line 47
    print "JottaFuse won't work without fusepy! Please run `pip install fusepy`."
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("JottaFuse won't work without fusepy! Please run `pip install fusepy`.")?
-----

Then I tried ghetto hacking by closing the print "" with () and ran the command again. Then I got this:

----
    from .jottafuse import JottaFuse
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jottalib/jottafuse.py", line 145
    'st_mode': stat.S_IFDIR | 0755,
                                 ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
----

**Comment by sjurtf** [comment]
No, at least not for GetSky customers. Use rclone (rclone.org) instead.

**Comment by ingardm** [comment]
Why not use the official client : https://docs.jottacloud.com/en/collections/178055-jottacloud-command-line-tool ?

**Comment by Antwelm** [comment]
> No, at least not for GetSky customers. Use rclone (rclone.org) instead.

I wasn't able to get that doing what I wanted (mounting locally), that's why I started trying jottalib. Will try the jottacloudCLI now, hopefully works for GetSky.

**Comment by Antwelm** [comment]
> Why not use the official client : https://docs.jottacloud.com/en/collections/178055-jottacloud-command-line-tool ?

Thanks, didn't know about that one. Got it and managed to login. But, I don't see any way of mounting stuff locally, which is what I want..
