### ISSUE TITLE
Propertly handle large files 

### ISSUE THREAD

**Issue by alexschrod** [havardgulldahl/jottalib#17]
jottacloudclientscanner.py seems to try to load the whole file that it's synching into memory. This gets problematic when the file size is close to the amount of free memory on the computer.

In my case, I was trying to sync a 2.8 GB file on a computer with 4 GB memory, of which about 3.6 GB were free when I started the jottacloudclientscanner.py program. This ended up being the output, after I watched the process gobble up more and more memory in top (it was at around 90% when this error popped up):

```
alex@fileserver:~$ jottacloudclientscanner.py /opt/safestore/Backups-encrypted/ /home/alex/jottafs/Home/Backups-encrypted/
ERROR:root:[Errno 2] No such file or directory: '/home/alex/.netrc'
Traceback (most recent call last):
  File "/usr/local/bin/jottacloudclientscanner.py", line 68, in <module>
    n = netrc.netrc()
  File "/usr/lib/python2.7/netrc.py", line 31, in __init__
    with open(file) as fp:
IOError: [Errno 2] No such file or directory: '/home/alex/.netrc'
Entering dir: /opt/safestore/Backups-encrypted/
Ouch. Something's wrong with "/opt/safestore/Backups-encrypted/sWURkzfhSLGRU9DaQB5U2x2A7lERmYYbjd36PUSSS8Mvt0":
ERROR:root:SAFERUN: Got exception when processing (u'/opt/safestore/Backups-encrypted/sWURkzfhSLGRU9DaQB5U2x2A7lERmYYbjd36PUSSS8Mvt0', u'/home/alex/jottafs/Home/Backups-encrypted/sWURkzfhSLGRU9DaQB5U2x2A7lERmYYbjd36PUSSS8Mvt0', <jottalib.JFS.JFS object at 0x2856c90>)
Traceback (most recent call last):
  File "/usr/local/bin/jottacloudclientscanner.py", line 85, in saferun
    return apply(cmd, args)
  File "/usr/local/lib/python2.7/dist-packages/jottacloudclient/jottacloud.py", line 88, in new
    _new = JFS.up(jottapath, lf)
  File "/usr/local/lib/python2.7/dist-packages/jottalib/JFS.py", line 695, in up
    return self.post(url, None, files=files, params=params, extra_headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/jottalib/JFS.py", line 644, in post
    r = self.session.post(url, data=content, params=params, files=files, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 424, in post
    return self.request('POST', url, data=data, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests_cache/core.py", line 110, in request
    hooks, stream, verify, cert)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 348, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 286, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 289, in prepare
    self.prepare_body(data, files)
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 426, in prepare_body
    (body, content_type) = self._encode_files(files, data)
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 144, in _encode_files
    body, content_type = encode_multipart_formdata(new_fields)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/filepost.py", line 93, in encode_multipart_formdata
    body.write(data)
MemoryError
```

**Comment by alexschrod** [comment]
Okay, I found one issue with the way I ran my code... I assumed the second argument was a jottafuse.py mount point. Still, running it with the "proper" location still causes this bug to take effect.

This is right before the program encountered another MemoryError. 89% memory use on a 4G program just won't do...:
![image](https://cloud.githubusercontent.com/assets/767490/5941245/f52ab8d0-a70f-11e4-85aa-d2b6e07cc3f7.png)

**Comment by alexschrod** [comment]
I have basically solved this problem. I want to pretty up the code I wrote a little, and then I'll commit it and make a pull request.

**Comment by jkaberg** [comment]
@havardgulldahl This one could be closed I guess? And this one https://github.com/havardgulldahl/jottalib/issues/10

**Comment by havardgulldahl** [comment]
I believe this is fixed, please reopen if you still have issues.
