### ISSUE TITLE
Create device folders (was: AttributeError: no such child: mountPoints)

### ISSUE THREAD

**Issue by jkaberg** [havardgulldahl/jottalib#26]
Tried mounting jottafuse today and got this 
```
jc@dunder:~# jottafuse.py --debug-http /media/jotta/
send: 'GET /jfs/**USERNAME** HTTP/1.1\r\nHost: www.jotta.no\r\nAccept-Encoding: identity\r\nX-JottaAPIVersion: 2.2\r\nAuthorization: Basic bXl1c2VybmFtZSUzQW15cGFzc3dvcmQ=\r\nUser-Agent: jottalib 0.2.10 (https://github.com/havardgulldahl/jottalib)\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Fri, 29 May 2015 07:24:20 GMT
header: Content-Type: text/xml
header: Transfer-Encoding: chunked
header: Server: Jetty(8.1.4.v20120524)
send: 'GET /jfs/**USERNAME**/ HTTP/1.1\r\nHost: www.jotta.no\r\nAccept-Encoding: identity\r\nX-JottaAPIVersion: 2.2\r\nAuthorization: Basic bXl1c2VybmFtZSUzQW15cGFzc3dvcmQ=\r\nUser-Agent: jottalib 0.2.10 (https://github.com/havardgulldahl/jottalib)\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Fri, 29 May 2015 07:24:25 GMT
header: Content-Type: text/xml
header: Transfer-Encoding: chunked
header: Server: Jetty(8.1.4.v20120524)
WARNING:root:Unknown jfs object: <type 'lxml.objectify.ObjectifiedElement'> <-> "user"
send: 'GET /jfs/**USERNAME**/ HTTP/1.1\r\nHost: www.jotta.no\r\nAccept-Encoding: identity\r\nX-JottaAPIVersion: 2.2\r\nAuthorization: Basic bXl1c2VybmFtZSUzQW15cGFzc3dvcmQ=\r\nUser-Agent: jottalib 0.2.10 (https://github.com/havardgulldahl/jottalib)\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Fri, 29 May 2015 07:24:26 GMT
header: Content-Type: text/xml
header: Transfer-Encoding: chunked
header: Server: Jetty(8.1.4.v20120524)
WARNING:root:Unknown jfs object: <type 'lxml.objectify.ObjectifiedElement'> <-> "user"
send: 'GET /jfs/**USERNAME**/Jotta/ HTTP/1.1\r\nHost: www.jotta.no\r\nAccept-Encoding: identity\r\nX-JottaAPIVersion: 2.2\r\nAuthorization: Basic bXl1c2VybmFtZSUzQW15cGFzc3dvcmQ=\r\nUser-Agent: jottalib 0.2.10 (https://github.com/havardgulldahl/jottalib)\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Fri, 29 May 2015 07:24:27 GMT
header: Content-Type: text/xml
header: Transfer-Encoding: chunked
header: Server: Jetty(8.1.4.v20120524)
send: 'GET /jfs/**USERNAME**/WIN-30L7VTADP6A/ HTTP/1.1\r\nHost: www.jotta.no\r\nAccept-Encoding: identity\r\nX-JottaAPIVersion: 2.2\r\nAuthorization: Basic bXl1c2VybmFtZSUzQW15cGFzc3dvcmQ=\r\nUser-Agent: jottalib 0.2.10 (https://github.com/havardgulldahl/jottalib)\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Fri, 29 May 2015 07:24:27 GMT
header: Content-Type: text/xml
header: Transfer-Encoding: chunked
header: Server: Jetty(8.1.4.v20120524)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 414, in _wrapper
    return func(*args, **kwargs) or 0
  File "/usr/local/lib/python2.7/dist-packages/fuse.py", line 602, in readdir
    fip.contents.fh):
  File "/usr/local/bin/jottafuse.py", line 193, in readdir
    for d in self.client.devices:
  File "/usr/local/lib/python2.7/dist-packages/jottalib/JFS.py", line 732, in devices
    return self.fs is not None and [JFSDevice(d, self, parentpath=self.rootpath) for d in self.fs.devices.iterchildren()] or [x for x in []]
  File "/usr/local/lib/python2.7/dist-packages/jottalib/JFS.py", line 457, in __init__
    self.mountPoints = {unicode(mp.name):mp for mp in self.mountpointobjects()}
  File "/usr/local/lib/python2.7/dist-packages/jottalib/JFS.py", line 467, in mountpointobjects
    return [ JFSMountPoint(obj, self._jfs, self.path) for obj in self.contents().mountPoints.iterchildren() ]
  File "lxml.objectify.pyx", line 218, in lxml.objectify.ObjectifiedElement.__getattr__ (src/lxml/lxml.objectify.c:3497)
  File "lxml.objectify.pyx", line 437, in lxml.objectify._lookupChildOrRaise (src/lxml/lxml.objectify.c:5947)
AttributeError: no such child: mountPoints

```

Just before I tried mounting I did a manuall update with
>pip install https://github.com/havardgulldahl/jottalib/archive/master.zip

**Comment by jkaberg** [comment]
Oddly enough, removing my "devices" from my account @ jotta.no solves the problem

**Comment by havardgulldahl** [comment]
Hmm. I don't understand quite what you did. Could you please give more detail?

**Comment by havardgulldahl** [comment]
If you could send me the output of what you get when you visit `https://www.jottacloud.com/jfs/**USERNAME**/WIN-30L7VTADP6A/` in a browser, that'd be grand. Send me a private message or email. Thanks!

**Comment by jkaberg** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>

<user time="2015-06-08-T18:16:36Z" host="dn-093.site-000.jotta.no">
  <username>******</username>
  <account-type>unlimited</account-type>
  <locked>false</locked>
  <capacity>-1</capacity>
  <max-devices>-1</max-devices>
  <max-mobile-devices>-1</max-mobile-devices>
  <usage>4406104</usage>
  <read-locked>false</read-locked>
  <write-locked>false</write-locked>
  <quota-write-locked>false</quota-write-locked>
  <enable-sync>false</enable-sync>
  <devices>
    <device>
      <name xml:space="preserve">JOEL-PC</name>
      <type>WORKSTATION</type>
      <sid>af9df295-e44f-46b7-8c95-480c4dd5a1e0</sid>
      <size>0</size>
      <modified></modified>
    </device>
    <device>
      <name xml:space="preserve">Jotta</name>
      <type>JOTTA</type>
      <sid>0555b50f-9704-4b11-94a9-9abaeec64d70</sid>
      <size>4406104</size>
      <modified>2015-06-08-T18:16:35Z</modified>
    </device>
  </devices>
</user>
```
And
```

<?xml version="1.0" encoding="UTF-8"?>

<device time="2015-06-08-T18:17:49Z" host="dn-094.site-000.jotta.no">
  <name xml:space="preserve">JOEL-PC</name>
  <type>WORKSTATION</type>
  <sid>af9df295-e44f-46b7-8c95-480c4dd5a1e0</sid>
  <size>0</size>
  <modified></modified>
  <user>get-45432659</user>
  <metadata first="" max="" total="0" num_mountpoints="0"/>
</device>
```

(I removed WIN-30L7VTADP6A since my last test)

**Comment by jkaberg** [comment]
Ok so I check this a bit more and came to the conclusion that device folders (the ones in /, eg /Jotta/ or /<choosen device name>/) can't be empty or we'll get the error 1st post. A workaround for now is obviously to create a folder with the official client first then use jottalib

**Comment by jkaberg** [comment]
Just had a thought about this @havardgulldahl , shouldn't we be able to create (device) folders in the root?

**Comment by havardgulldahl** [comment]
I don't know the api to do that. Will you be able to provide me with some logs of doing it?

**Comment by havardgulldahl** [comment]
Pushing this to 0.4, we need to see some logs of how the official client does it
