### ISSUE TITLE
Issue with resuming

### ISSUE THREAD

**Issue by cowai** [havardgulldahl/jottalib#81]
```shell
user@nas:~$ jotta-scanner /bigpool/video/tv /machine-name/jotta/bigpool/video/
Ouch. Something's wrong with "/bigpool/video/tv/Show/S02/Show.S02E07.mkv":  
ERROR:jottalib.scanner:SAFERUN: Got exception when processing (u'/bigpool/video/tv/Show/S02/Show.S02E07.mkv', u'/machine-name/jotta/bigpool/video/tv/Show/S02/Show.S02E07.mkv', <jottalib.JFS.JFS object at 0x7f045c4af390>)  
Traceback (most recent call last):  
  File "build/bdist.linux-x86_64/egg/jottalib/scanner.py", line 54, in saferun  
    return apply(cmd, args)  
  File "build/bdist.linux-x86_64/egg/jottalib/jottacloud.py", line 151, in replace_if_changed  
    return resume(localfile, jf, JFS)  
  File "build/bdist.linux-x86_64/egg/jottalib/jottacloud.py", line 135, in resume  
    _complete = jottafile.resume(lf)  
  File "build/bdist.linux-x86_64/egg/jottalib/JFS.py", line 377, in resume  
    return self.jfs.up(self.path, data, resume_offset=self.size)  
  File "build/bdist.linux-x86_64/egg/jottalib/JFS.py", line 940, in up  
    fileobject.seek(resume_offset if resume_offset is not None else 0)  
IOError: [Errno 22] Invalid argument  
comparing 7 existing files: [################################] 7/7 - 00:00:07

**Comment by havardgulldahl** [comment]
Hey @cowai, what size is the actual file?

I'm guessing this is related to #104, seems like the same thing.

**Comment by cowai** [comment]
@havardgulldahl I dont remember now, but I guess it would be around 4gb.
