### ISSUE TITLE
Downloading files and folders with Swedish letters fails

### ISSUE THREAD

**Issue by antonhagg** [havardgulldahl/jottalib#86]
There seem to be some problem downloading files and folders that have Swedish letters (åäö).
The problem seem to be in urllib.py and in posixpath.py but is there something we can do in jottalib to prevent this to happend?

```
WARNING:py.warnings:c:\python27\lib\urllib.py:1303: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  return ''.join(map(quoter, s))

Traceback (most recent call last):
  File "C:\Python27\Scripts\jotta-download-script.py", line 9, in <module>
    load_entry_point('jottalib==0.4.1.post1', 'console_scripts', 'jotta-download')()
  File "c:\python27\lib\site-packages\jottalib\cli.py", line 273, in download
    remote_object = jfs.getObject(abs_path_to_object)
  File "c:\python27\lib\site-packages\jottalib\JFS.py", line 851, in getObject
    o = self.get(url)
  File "c:\python27\lib\site-packages\jottalib\JFS.py", line 838, in get
    url = self.escapeUrl(url)
  File "c:\python27\lib\site-packages\jottalib\JFS.py", line 807, in escapeUrl
    url = quote(urlparts[0], safe=self.rootpath)
  File "c:\python27\lib\urllib.py", line 1303, in quote
    return ''.join(map(quoter, s))
KeyError: u'\xe5'
```

```
jotta-download -c -v åäö.pdf
Traceback (most recent call last):
  File "C:\Python27\Scripts\jotta-download-script.py", line 9, in <module>
    load_entry_point('jottalib==0.4.1.post1', 'console_scripts', 'jotta-download')()
  File "c:\python27\lib\site-packages\jottalib\cli.py", line 226, in download
    path_to_object = posixpath.join(root_folder.path, args.remoteobject)
  File "c:\python27\lib\posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 1: ordinal not in range(128)
```

**Comment by antonhagg** [comment]
Update: This is also the case for Norwegian letters.

**Comment by antonhagg** [comment]
Encoding the url in get() seems to fix the problem, at least for the first error (see code below). 
The second error I have no idea how to fix. Printing the value gives me "Õõ÷.pdf" so there might be something going on with the input from the command line (in windows).
 
```python
def get(self, url):
        'Make a GET request for url and return the response content as a generic lxml object'    
        url = url.encode(encoding='UTF-8')
        url = self.escapeUrl(url)
```

**Comment by dahlSTROM** [comment]
@antonhagg Did you ever manage to solve this? I'm still having issues with jotta-scanner and uploading folders containing ÅÄÖ. The path gets messed up in the dict for some reason. Here's an example:

```python
Ouch. Something's wrong with "/mnt/nas4free/Pictures/Småland 010512-13/DCP_0366.JPG":
ERROR:jottalib.scanner:SAFERUN: Got exception when processing (u'/mnt/nas4free/Pictures/Sm\xe5land 010512-13/DCP_0366.JPG', u'/Jotta/Archive/Sm\xe5land 010512-13/DCP_0366.JPG', <jottalib.JFS.JFS object at 0x7f093b711990>)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/jottalib/scanner.py", line 54, in saferun
    return apply(cmd, args)
  File "/usr/local/lib/python2.7/dist-packages/jottalib/jottacloud.py", line 129, in new
    _new = JFS.up(jottapath, lf)
  File "/usr/local/lib/python2.7/dist-packages/jottalib/JFS.py", line 993, in up
    return self.post(url, None, files=files, params=params, extra_headers=headers, upload_callback=upload_callback)
  File "/usr/local/lib/python2.7/dist-packages/jottalib/JFS.py", line 926, in post
    url = self.escapeUrl(url)
  File "/usr/local/lib/python2.7/dist-packages/jottalib/JFS.py", line 820, in escapeUrl
    url = quote(urlparts[0], safe=self.rootpath)
  File "/usr/lib/python2.7/urllib.py", line 1294, in quote
    return ''.join(map(quoter, s))
KeyError: u'\xe5'
```

**Comment by havardgulldahl** [comment]
Guys, thanks for your patience, I have started working on unicode/character encoding issues.
