### ISSUE TITLE
jottalib.contrib not included by setup.py (was: FUSE error)

### ISSUE THREAD

**Issue by jnylen** [havardgulldahl/jottalib#90]
Hi,
I install jottalib through pip and wanted to try to use FUSE but the recent version seemed to have bugged it out completely. FUSEPY is installed already but it still complains:

> jotta-fuse /home/jnylen/jottsfs

`Traceback (most recent call last):
  File "/usr/local/bin/jotta-fuse", line 11, in <module>
    sys.exit(fuse())
  File "/usr/local/lib/python3.4/dist-packages/jottalib/cli.py", line 103, in fuse
    from .jottafuse import JottaFuse
  File "/usr/local/lib/python3.4/dist-packages/jottalib/jottafuse.py", line 47
    print "JottaFuse won't work without fusepy! Please run 'pip install fusepy'."
                                                                                ^
SyntaxError: Missing parentheses in call to 'print'`

**Comment by havardgulldahl** [comment]
That would be a py3 bug on top of a missing import.

Please try to install jottalib in a py2 environment and report back if it still doesn't work.

**Comment by jnylen** [comment]
On python 2 I see this:

`Traceback (most recent call last):
  File "/usr/local/bin/jotta-fuse", line 11, in <module>
    sys.exit(fuse())
  File "/usr/local/lib/python2.7/dist-packages/jottalib/cli.py", line 103, in fuse
    from .jottafuse import JottaFuse
  File "/usr/local/lib/python2.7/dist-packages/jottalib/jottafuse.py", line 41, in <module>
    from jottalib.contrib.mwt import Memoize
ImportError: No module named contrib.mwt
`

**Comment by jnylen** [comment]
Everything else seems to work well though. But I need to use FUSE for some stuff I do.

**Comment by jnylen** [comment]
And on jotta-monitor this occurs:

`
Traceback (most recent call last):
  File "/usr/local/bin/jotta-monitor", line 11, in <module>
    sys.exit(monitor())
  File "/usr/local/lib/python2.7/dist-packages/jottalib/cli.py", line 340, in monitor
    from .monitor import filemonitor
  File "/usr/local/lib/python2.7/dist-packages/jottalib/monitor.py", line 36, in <module>
    from jottalib.contrib.readlnk import readlnk
ImportError: No module named contrib.readlnk
`

So it seems anything in the module contrib can't be found.

**Comment by havardgulldahl** [comment]
Is this git or 0.4.1?

Skrevet med tommelen




On Mon, Feb 1, 2016 at 8:36 AM -0800, "Joakim Nylén" <notifications@github.com> wrote:












And on jotta-monitor this occurs:





Traceback (most recent call last):

  File "/usr/local/bin/jotta-monitor", line 11, in <module>

    sys.exit(monitor())

  File "/usr/local/lib/python2.7/dist-packages/jottalib/cli.py", line 340, in monitor

    from .monitor import filemonitor

  File "/usr/local/lib/python2.7/dist-packages/jottalib/monitor.py", line 36, in <module>

    from jottalib.contrib.readlnk import readlnk

ImportError: No module named contrib.readlnk





So it seems anything in the module contrib can't be found.

**Comment by jnylen** [comment]
Hi,
This was installed from pip. So I guess it's 0.4.1.

**Comment by havardgulldahl** [comment]
Ouch, that sucks. Don't know why you're getting those errors, the tests should've caught it. 

I'm looking into it now.

**Comment by havardgulldahl** [comment]
Yes, you're right. After poking around a bit, `jottalib.contrib` is not even included in `setup.py`. I'll cut a new release asap. Thanks for your report.

**Comment by havardgulldahl** [comment]
Please try with the newly released 0.4.2 and report back if you have any issues.
